# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da70b0ece3d628a0282571602e8a707be4389361fbfb298eb0bb9e374e919aba898a459d824dd6561a9d6ac5c97626db8a26cff48166700131c8ae66bd3eb771

test:
  secret_key_base: 2b7a7d27ed282fa2817191db2912aec496629de5750efba2d352a62c776c6ecc39a0dda38cea5ca96a7ee993ec4c3b6060bab138e9d9e0fe5b7b07a6667bad56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
